CREATE DATABASE langLearn;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    lessonId INT(255) NOT NULL,
    languageId INT(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE lessons(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    languageId INT(255) NOT NULL
);

CREATE TABLE languages(
    id SERIAL PRIMARY KEY,
    languageName VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE flashCards(
    id SERIAL PRIMARY KEY,
    lessonId INT(255) NOT NULL
);

CREATE TABLE tips(
    id SERIAL PRIMARY KEY,
    lessonId INT(255) NOT NULL
);



